### ISSUE TITLE
Crash on Symfony project import: Background Indexer Crash'

### ISSUE THREAD

**Issue by pgnd** [pulse00/Symfony-2-Eclipse-Plugin#233]
I'm running

Eclipse, Version: Mars (4.5). Build id: I20150603-2000
Symfony2EclipsePlugin v.1.1.0.201506240812

on linux/64.

On exec of an import of an existing SymfonyProject:

  Project Explorer -> Import ... -> SymfonyProject

After entering ProjectName & SourceFolder, then clicking 'Finish', I get a dialog:

"Error occured duing import.  Please see workspace logs ..."

Tail of the logs during this procedure:

```
!ENTRY org.eclipse.dltk.core 4 4 2015-07-03 20:05:25.067
!MESSAGE Background Indexer Crash Recovery
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.compiler.ast.nodes.PHPDocTag.getReferences()[Lorg/eclipse/dltk/ast/references/SimpleReference;
        at com.dubture.symfony.core.index.SymfonyIndexingVisitorExtension.visit(SymfonyIndexingVisitorExtension.java:389)
        at org.eclipse.php.internal.core.index.PhpIndexingVisitor.visit(PhpIndexingVisitor.java:359)
        at org.eclipse.dltk.ast.declarations.MethodDeclaration.traverse(MethodDeclaration.java:70)
        at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
        at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:158)
        at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
        at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
        at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
        at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
        at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
        at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
        at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
        at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
        at java.lang.Thread.run(Thread.java:745)
```

Can provide add'l detail as needed.

**Comment by zulus** [comment]
I published new version to p2-dev repo. Symfony plugin is again synced with PDT nightly.

**Comment by pgnd** [comment]
grabbed & installed the update.

still fails, but with only these errors:

```
!ENTRY com.dubture.composer.core 1 1 2015-07-05 15:01:52.479
!MESSAGE loading namespacemap from preferences for project .com_puppetlabs_geppetto_pptp_target {}

!ENTRY com.dubture.composer.core 1 1 2015-07-05 15:01:52.479
!MESSAGE loading namespacemap from preferences for project RemoteSystemsTempFiles {}

!ENTRY com.dubture.composer.core 1 1 2015-07-05 15:01:52.479
!MESSAGE loading namespacemap from preferences for project WebTEST {}
```

Digging ...

**Comment by zulus** [comment]
This is normal log from composer plugin during buildpath update.

**Comment by pgnd** [comment]
had to change

-   /usr/local/bin/eclipse -debug .options
+    /usr/local/bin/eclipse -debug /usr/local/eclipse/.options

because here

/usr/local/bin/eclipse is a symlink to /usr/local/eclipse/bin/eclipse.

with that, on repeat of the process

```
!ENTRY com.dubture.symfony.core 0 0 2015-07-05 15:17:43.994
!MESSAGE null
!STACK 0
java.lang.IllegalArgumentException
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.setProjectFacetActionConfig(FacetedProjectWorkingCopy.java:1629)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:320)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
        at com.dubture.symfony.core.facet.FacetManager.installFacets(FacetManager.java:63)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard$1.run(SymfonyImportWizard.java:126)
        at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
        at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard.performFinish(SymfonyImportWizard.java:155)
        at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
        at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
        at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
        at org.eclipse.jface.window.Window.open(Window.java:803)
        at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:158)
        at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
        at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:160)
        at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:175)
        at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:99)
        at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:170)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY com.dubture.symfony.core 0 0 2015-07-05 15:17:44.708
!MESSAGE Resource '/WebTEST' is not open.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/WebTEST' is not open.
        at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:143)
        at org.eclipse.core.internal.resources.Project.getNature(Project.java:406)
        at com.dubture.symfony.core.index.SymfonyIndexingVisitorExtension.setSourceModule(SymfonyIndexingVisitorExtension.java:100)
        at org.eclipse.php.internal.core.index.PhpIndexingVisitor.<init>(PhpIndexingVisitor.java:116)
        at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
        at com.dubture.symfony.core.index.SymfonyIndexingParser.parseSourceModule(SymfonyIndexingParser.java:37)
        at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
        at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
        at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
        at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
        at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
        at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 1 org.eclipse.core.resources 4 372 2015-07-05 15:17:44.708
!MESSAGE Resource '/WebTEST' is not open.

!ENTRY com.dubture.symfony.core 0 0 2015-07-05 15:17:44.712
!MESSAGE Resource '/WebTEST' is not open.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/WebTEST' is not open.
        at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:143)
        at org.eclipse.core.internal.resources.Project.getNature(Project.java:406)
        at com.dubture.symfony.core.index.SymfonyIndexingVisitorExtension.setSourceModule(SymfonyIndexingVisitorExtension.java:100)
        at org.eclipse.php.internal.core.index.PhpIndexingVisitor.<init>(PhpIndexingVisitor.java:116)
        at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
        at com.dubture.symfony.core.index.SymfonyIndexingParser.parseSourceModule(SymfonyIndexingParser.java:37)
        at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
        at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
        at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
        at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
        at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
        at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 1 org.eclipse.core.resources 4 372 2015-07-05 15:17:44.712
!MESSAGE Resource '/WebTEST' is not open.
```

not sure why it's complaining about '/WebTEST'' since I'm entering just 'test' in the dialog.  Something cached maybe?

**Comment by zulus** [comment]
You haven't php executables in your eclipse configuration. I published update, if your eclipse won't update restart it or go to Preferences -> Install/Update -> Available Software Sites , select pex repository and run reload.

**Comment by pgnd** [comment]
yes, I do.  I have a php executable defined @ location "/usr/local/php5/bin/php", where

```
/usr/local/php5/bin/php -v
PHP 5.6.12-dev (cli) (built: Jun 30 2015 20:45:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Let me see what I can figure out with that 'pex' repo.

**Comment by pgnd** [comment]
What exactly do you mean my the 'pex' repository?

I alread have installed & active:

  http://p2-dev.pdt-extensions.org/

I re-ran update.

It grabbed:

	Symfony Feature 1.1.1.201507052245

rebooted eclipse.

enter:

	Project name: [test]
	Source folder: /srv/www/test/symfony

then

	Dumped container:
	Symfony console:

autopopulate, and the value for 

	Project name: [test]

is changed automatically to

	Project name: [WebTEST]

On click of "Finish", same error

with these logs

```
!ENTRY com.dubture.symfony.core 0 0 2015-07-05 16:16:11.807
!MESSAGE null
!STACK 0
java.lang.IllegalArgumentException
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.setProjectFacetActionConfig(FacetedProjectWorkingCopy.java:1629)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:320)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
        at com.dubture.symfony.core.facet.FacetManager.installFacets(FacetManager.java:63)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard$1.run(SymfonyImportWizard.java:126)
        at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
        at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard.performFinish(SymfonyImportWizard.java:155)
        at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
        at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
        at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
        at org.eclipse.jface.window.Window.open(Window.java:803)
        at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:158)
        at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
        at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:160)
        at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:175)
        at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:99)
        at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:170)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY com.dubture.symfony.core 0 0 2015-07-05 16:16:11.855
!MESSAGE Attempted to beginRule: R/, does not match outer scope rule: P/WebTEST
!STACK 0
java.lang.IllegalArgumentException: Attempted to beginRule: R/, does not match outer scope rule: P/WebTEST
        at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
        at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
        at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:333)
        at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:63)
        at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:307)
        at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:120)
        at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2189)
        at org.eclipse.core.internal.resources.File.create(File.java:105)
        at org.eclipse.core.internal.resources.ProjectPreferences$1.run(ProjectPreferences.java:640)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
        at org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.java:662)
        at org.eclipse.core.internal.preferences.EclipsePreferences.internalFlush(EclipsePreferences.java:471)
        at org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.java:365)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard.createProjectSettings(SymfonyImportWizard.java:191)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard$1.run(SymfonyImportWizard.java:128)
        at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
        at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
        at com.dubture.symfony.ui.wizards.importer.SymfonyImportWizard.performFinish(SymfonyImportWizard.java:155)
        at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
        at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
        at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
        at org.eclipse.jface.window.Window.open(Window.java:803)
        at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:158)
        at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
        at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:160)
        at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:175)
        at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:99)
        at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:170)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY com.dubture.symfony.core 0 0 2015-07-05 16:16:12.643
!MESSAGE Resource '/WebTEST' is not open.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/WebTEST' is not open.
        at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:143)
        at org.eclipse.core.internal.resources.Project.getNature(Project.java:406)
        at com.dubture.symfony.core.index.SymfonyIndexingVisitorExtension.setSourceModule(SymfonyIndexingVisitorExtension.java:100)
        at org.eclipse.php.internal.core.index.PhpIndexingVisitor.<init>(PhpIndexingVisitor.java:116)
        at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
        at com.dubture.symfony.core.index.SymfonyIndexingParser.parseSourceModule(SymfonyIndexingParser.java:37)
        at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
        at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
        at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
        at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
        at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
        at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 1 org.eclipse.core.resources 4 372 2015-07-05 16:16:12.643
!MESSAGE Resource '/WebTEST' is not open.

!ENTRY com.dubture.symfony.core 0 0 2015-07-05 16:16:12.651
!MESSAGE Resource '/WebTEST' is not open.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/WebTEST' is not open.
        at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:143)
        at org.eclipse.core.internal.resources.Project.getNature(Project.java:406)
        at com.dubture.symfony.core.index.SymfonyIndexingVisitorExtension.setSourceModule(SymfonyIndexingVisitorExtension.java:100)
        at org.eclipse.php.internal.core.index.PhpIndexingVisitor.<init>(PhpIndexingVisitor.java:116)
        at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
        at com.dubture.symfony.core.index.SymfonyIndexingParser.parseSourceModule(SymfonyIndexingParser.java:37)
        at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
        at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
        at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
        at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
        at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
        at java.lang.Thread.run(Thread.java:745)
!SUBENTRY 1 org.eclipse.core.resources 4 372 2015-07-05 16:16:12.651
!MESSAGE Resource '/WebTEST' is not open.
```

**Comment by pgnd** [comment]
fyi, currently

![dubture](https://cloud.githubusercontent.com/assets/5993465/8513905/e5d1ead0-2332-11e5-8655-c7c63167e5f3.png)

**Comment by zulus** [comment]
which symfony version have your project?

**Comment by pgnd** [comment]
```
 php app/console --version
  Symfony version 2.7.1 - app/dev/debug
```

**Comment by zulus** [comment]
have you standard dir structure or 3.0?

**Comment by pgnd** [comment]
standard.  unaltered from that installed by the symfony installer.

**Comment by zulus** [comment]
Can you run ./app/console before import?

**Comment by pgnd** [comment]
Sry, not clear what you're asking ...

Am I *able* to run app/console?  Yes, as above .  I guess you mean something else?

**Comment by zulus** [comment]
In other words, have you app/cache/dev/appDevDebugProjectContainer.xml file?

Anyway I'm not able to reproduce right now.
Workaround:
* File -> New -> PHP Project
* select "existing source" and "enable javascript support"
* finish
* wait a moment
* right click on project -> configure -> add composer support
* right click on project -> configure -> add symfony support

**Comment by pgnd** [comment]
Yes, I have that file.

I'll give that workaround a try later this eve.  Thanks.

**Comment by pgnd** [comment]
>    File -> New -> PHP Project
done

>    select "existing source" and "enable javascript support"

no such options
![dubture1](https://cloud.githubusercontent.com/assets/5993465/8515456/b777f5c4-2357-11e5-93c8-edbb133aabfc.png)

>    finish
>    wait a moment

done

>    right click on project -> configure -> add composer support
>    right click on project -> configure -> add symfony support

options not available

1st had to add 'PHP support'

THEN
 -> add composer support
 -> add symfony support

at this point I end up with 

Project Explorer
  "test"
    Connections

Not at all clear how one adds the existing SymfonyProject to this tree.

**Comment by zulus** [comment]
This is not PDT new PHP Project page, how it should look:

[PDT New Project](http://i.imgur.com/WzrTrU6.png)

**Comment by pgnd** [comment]
not sure what to do about that ... 'my' screenshot clearly says "new php project: create a new php project"

**Comment by zulus** [comment]
But this is "new php project" from aptana or phpeclipse, not from eclipse PDT. 

Can you open php perspective? In this perspective File -> New contain valid "PHP Project" creator wizard.

**Comment by pgnd** [comment]
I stumbled on at least one cause of the problem  -- a preexisting hidden ".project" file, apparently populated with 'dubture' data -- in the root of the project.  No matter the file's perms, I'd get this error.  RM'ing the file, now an import procedure works with no error, and I can subsequently edit it.

Something about that preexisting file ... I *did* notice that it contained the 'webTEST' title that kept overwriting the title I entered.

**Comment by zulus** [comment]
Thanks! I'll test it soon.
